title: AdSDK Documentation
baseurl: "/nextgen-adsdk-android-release"
url: "https://vm-mobile-sdk.github.io"
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
collections_dir: tutorials
collections:
  6.0.0:
    output: true
  5.3.0:
    output: true
  5.0.1:
    output: true
  5.0.0:
    output: true
  4.6.0:
    output: true

just_the_docs:
  collections:
    6.0.0:
      name: SDK v.6.0.0
      nav_fold: true
    5.3.0:
      name: SDK v.5.3.0
      nav_fold: true
    5.0.1:
      name: SDK v.5.0.1
      nav_fold: true
    5.0.0:
      name: SDK v.5.0.0
      nav_fold: true
    4.6.0:
      name: SDK v.4.6.0
      nav_fold: true
